// <auto-generated />
using System;
using ElectronicMedicalCert.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronicMedicalCert.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ElectronicMedicalCertDbContext))]
    [Migration("20260424173932_Seed_Termx_Remaining_Codelists")]
    partial class Seed_Termx_Remaining_Codelists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.AuthorizedWorker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KrzpId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Ico", "KrzpId")
                        .IsUnique();

                    b.ToTable("AuthorizedWorkers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Ico = "12345678",
                            KrzpId = "KRZP-001"
                        });
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.Codebook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PlatnostDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlatnostOd")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Termx")
                        .HasColumnType("bit");

                    b.Property<string>("TermxId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TermxUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Verze")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Codebooks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Kod = "STAV-POSUDKU",
                            PlatnostOd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Kod = "TYP-AKCE",
                            PlatnostOd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Kod = "DRUH-PROHLIDKY",
                            PlatnostOd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Kod = "DRUH-POSUDKU",
                            PlatnostOd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Kod = "VYSLEDEK",
                            PlatnostOd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Kod = "SKUPINA-ZADATEL-RIDIC",
                            PlatnostOd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Kod = "SKUPINA-RO",
                            PlatnostOd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Kod = "TYP-OPERACE",
                            PlatnostOd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Kod = "ODBORNOST-LEKARE",
                            PlatnostOd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000a"),
                            Kod = "HARMON-KOD",
                            PlatnostOd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-00000000000b"),
                            Kod = "NAROD-KOD",
                            PlatnostOd = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Verze = "1"
                        });
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.CodebookItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodebookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("RodicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Verze")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CodebookId");

                    b.ToTable("CodebookItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Kod = "stav_posudku_platny",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Kod = "stav_posudku_zneplatneny",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Kod = "akce_ro_vytvoreni",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Kod = "akce_ro_zneplatneni",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Kod = "druh_prohlidky_ro_vstupni",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000006"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Kod = "druh_prohlidky_ro_periodicka",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000007"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Kod = "druh_prohlidky_ro_mimoradna",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Kod = "druh_posudku_ro",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000007"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Kod = "vysledek_posudku_ro_zpusobily",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000008"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Kod = "vysledek_posudku_ro_nezpusobily",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-00000000000b"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Kod = "vysledek_posudku_ro_zpusobily_s_podminkou",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000009"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Kod = "skupina_ro_1",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-00000000000d"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Kod = "skupina_ro_2",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000a"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Kod = "B",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000b"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Kod = "CREATE",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000c"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Kod = "INVALIDATE",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000d"),
                            CodebookId = new Guid("20000000-0000-0000-0000-000000000009"),
                            Kod = "VSEOBECNY",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000e"),
                            CodebookId = new Guid("20000000-0000-0000-0000-00000000000a"),
                            Kod = "01",
                            Verze = "1"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-00000000000f"),
                            CodebookId = new Guid("20000000-0000-0000-0000-00000000000b"),
                            Kod = "N01",
                            Verze = "1"
                        });
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DatumVystaveni")
                        .HasColumnType("date");

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DruhPosudkuPolozkaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DruhProhlidkyPolozkaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KrzpId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("OpakovanyPosudekId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("PlatnostDo")
                        .HasColumnType("date");

                    b.Property<string>("Rid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("StavPosudkuPolozkaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TypAkcePolozkaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PosudkyRo");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRoHarmonizovanyKod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HarmonizovanyKodPolozkaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosudekRoZpusobilostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpresneniText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PosudekRoZpusobilostId");

                    b.ToTable("PosudekRoHarmonizovanyKod");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRoHarmonizovanyKodSkupinaRo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosudekRoHarmonizovanyKodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkupinaRoPolozkaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PosudekRoHarmonizovanyKodId");

                    b.ToTable("PosudekRoHarmonizovanyKodSkupinaRo");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRoHistorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumOperace")
                        .HasColumnType("datetime2");

                    b.Property<string>("IcoPoskytovatele")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KrzpIdLekare")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PosudekRoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TypOperacePolozkaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PosudekRoId");

                    b.ToTable("PosudkyRoHistorie");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRoNarodniKod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NarodniKodPolozkaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosudekRoZpusobilostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkupinaRoPolozkaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpresneniText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PosudekRoZpusobilostId");

                    b.ToTable("PosudekRoNarodniKod");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRoSkupina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosudekRoZpusobilostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkupinaRoPolozkaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PosudekRoZpusobilostId");

                    b.ToTable("PosudekRoSkupina");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRoZpusobilost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosudekRoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SkupinaZadateleRidicPolozkaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VysledekPolozkaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PosudekRoId");

                    b.ToTable("PosudkyRoZpusobilosti");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.Codebook", b =>
                {
                    b.OwnsMany("ElectronicMedicalCert.Domain.Entities.Translation", "Preklady", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CodebookId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Nazev")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Popis")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.HasKey("Id");

                            b1.HasIndex("CodebookId");

                            b1.ToTable("CodebookTranslations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CodebookId");

                            b1.HasData(
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000001"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000001"),
                                    Language = "cs",
                                    Nazev = "Stav posudku",
                                    Popis = "Stavy posudků."
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000002"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000001"),
                                    Language = "en",
                                    Nazev = "Certificate state",
                                    Popis = "Certificate states."
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000003"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000002"),
                                    Language = "cs",
                                    Nazev = "Typ akce"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000004"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000002"),
                                    Language = "en",
                                    Nazev = "Action type"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000005"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000003"),
                                    Language = "cs",
                                    Nazev = "Druh prohlídky"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000006"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000003"),
                                    Language = "en",
                                    Nazev = "Exam type"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000007"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000004"),
                                    Language = "cs",
                                    Nazev = "Druh posudku"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000008"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000004"),
                                    Language = "en",
                                    Nazev = "Certificate type"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000009"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000005"),
                                    Language = "cs",
                                    Nazev = "Výsledek"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-00000000000a"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000005"),
                                    Language = "en",
                                    Nazev = "Result"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-00000000000b"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000006"),
                                    Language = "cs",
                                    Nazev = "Skupina žadatele"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-00000000000c"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000006"),
                                    Language = "en",
                                    Nazev = "Applicant group"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-00000000000d"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000007"),
                                    Language = "cs",
                                    Nazev = "Skupiny ŘO"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-00000000000e"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000007"),
                                    Language = "en",
                                    Nazev = "Driving licence groups"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-00000000000f"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000008"),
                                    Language = "cs",
                                    Nazev = "Typ operace"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000010"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000008"),
                                    Language = "en",
                                    Nazev = "Operation type"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000011"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000009"),
                                    Language = "cs",
                                    Nazev = "Odbornost"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000012"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-000000000009"),
                                    Language = "en",
                                    Nazev = "Specialization"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000013"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-00000000000a"),
                                    Language = "cs",
                                    Nazev = "Harmonizované kódy"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000014"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-00000000000a"),
                                    Language = "en",
                                    Nazev = "Harmonized codes"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000015"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-00000000000b"),
                                    Language = "cs",
                                    Nazev = "Národní kódy"
                                },
                                new
                                {
                                    Id = new Guid("40000000-0000-0000-0000-000000000016"),
                                    CodebookId = new Guid("20000000-0000-0000-0000-00000000000b"),
                                    Language = "en",
                                    Nazev = "National codes"
                                });
                        });

                    b.Navigation("Preklady");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.CodebookItem", b =>
                {
                    b.HasOne("ElectronicMedicalCert.Domain.Entities.Codebook", "Codebook")
                        .WithMany("Polozky")
                        .HasForeignKey("CodebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("ElectronicMedicalCert.Domain.Entities.Translation", "Preklady", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("CodebookItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("Nazev")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Popis")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.HasKey("Id");

                            b1.HasIndex("CodebookItemId");

                            b1.ToTable("CodebookItemTranslations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CodebookItemId");

                            b1.HasData(
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000001"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000001"),
                                    Language = "cs",
                                    Nazev = "Platný"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000002"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000001"),
                                    Language = "en",
                                    Nazev = "Valid"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000003"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000002"),
                                    Language = "cs",
                                    Nazev = "Zneplatněný"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000004"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000002"),
                                    Language = "en",
                                    Nazev = "Invalidated"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000005"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000003"),
                                    Language = "cs",
                                    Nazev = "Vytvoření"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000006"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000003"),
                                    Language = "en",
                                    Nazev = "Creation"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000007"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000004"),
                                    Language = "cs",
                                    Nazev = "Zneplatnění"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000008"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000004"),
                                    Language = "en",
                                    Nazev = "Invalidation"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000009"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000005"),
                                    Language = "cs",
                                    Nazev = "Vstupní prohlídka"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-00000000000a"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000005"),
                                    Language = "en",
                                    Nazev = "Initial examination"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-00000000000b"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000006"),
                                    Language = "cs",
                                    Nazev = "Řidičské oprávnění"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-00000000000c"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000006"),
                                    Language = "en",
                                    Nazev = "Driving licence"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-00000000000d"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000007"),
                                    Language = "cs",
                                    Nazev = "Způsobilý"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-00000000000e"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000007"),
                                    Language = "en",
                                    Nazev = "Fit"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-00000000000f"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000008"),
                                    Language = "cs",
                                    Nazev = "Nezpůsobilý"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000010"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000008"),
                                    Language = "en",
                                    Nazev = "Unfit"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000011"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000009"),
                                    Language = "cs",
                                    Nazev = "Skupina 1"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000012"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-000000000009"),
                                    Language = "en",
                                    Nazev = "Group 1"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000013"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-00000000000a"),
                                    Language = "cs",
                                    Nazev = "B"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000014"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-00000000000a"),
                                    Language = "en",
                                    Nazev = "B"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000015"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-00000000000b"),
                                    Language = "cs",
                                    Nazev = "Vytvoření"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000016"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-00000000000b"),
                                    Language = "en",
                                    Nazev = "Create"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000017"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-00000000000c"),
                                    Language = "cs",
                                    Nazev = "Zneplatnění"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000018"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-00000000000c"),
                                    Language = "en",
                                    Nazev = "Invalidate"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-000000000019"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-00000000000d"),
                                    Language = "cs",
                                    Nazev = "Všeobecný lékař"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-00000000001a"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-00000000000d"),
                                    Language = "en",
                                    Nazev = "General practitioner"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-00000000001b"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-00000000000e"),
                                    Language = "cs",
                                    Nazev = "01"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-00000000001c"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-00000000000e"),
                                    Language = "en",
                                    Nazev = "01"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-00000000001d"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-00000000000f"),
                                    Language = "cs",
                                    Nazev = "N01"
                                },
                                new
                                {
                                    Id = new Guid("50000000-0000-0000-0000-00000000001e"),
                                    CodebookItemId = new Guid("30000000-0000-0000-0000-00000000000f"),
                                    Language = "en",
                                    Nazev = "N01"
                                },
                                new
                                {
                                    Id = new Guid("90000000-0000-0000-0000-00000000000b"),
                                    CodebookItemId = new Guid("80000000-0000-0000-0000-000000000006"),
                                    Language = "cs",
                                    Nazev = "Periodická prohlídka"
                                },
                                new
                                {
                                    Id = new Guid("90000000-0000-0000-0000-00000000000c"),
                                    CodebookItemId = new Guid("80000000-0000-0000-0000-000000000006"),
                                    Language = "en",
                                    Nazev = "Periodic examination"
                                },
                                new
                                {
                                    Id = new Guid("90000000-0000-0000-0000-00000000000d"),
                                    CodebookItemId = new Guid("80000000-0000-0000-0000-000000000007"),
                                    Language = "cs",
                                    Nazev = "Mimořádná prohlídka"
                                },
                                new
                                {
                                    Id = new Guid("90000000-0000-0000-0000-00000000000e"),
                                    CodebookItemId = new Guid("80000000-0000-0000-0000-000000000007"),
                                    Language = "en",
                                    Nazev = "Extraordinary examination"
                                },
                                new
                                {
                                    Id = new Guid("90000000-0000-0000-0000-000000000015"),
                                    CodebookItemId = new Guid("80000000-0000-0000-0000-00000000000b"),
                                    Language = "cs",
                                    Nazev = "Způsobilý s podmínkou"
                                },
                                new
                                {
                                    Id = new Guid("90000000-0000-0000-0000-000000000016"),
                                    CodebookItemId = new Guid("80000000-0000-0000-0000-00000000000b"),
                                    Language = "en",
                                    Nazev = "Fit with condition"
                                },
                                new
                                {
                                    Id = new Guid("90000000-0000-0000-0000-000000000019"),
                                    CodebookItemId = new Guid("80000000-0000-0000-0000-00000000000d"),
                                    Language = "cs",
                                    Nazev = "Skupina 2"
                                },
                                new
                                {
                                    Id = new Guid("90000000-0000-0000-0000-00000000001a"),
                                    CodebookItemId = new Guid("80000000-0000-0000-0000-00000000000d"),
                                    Language = "en",
                                    Nazev = "Group 2"
                                });
                        });

                    b.Navigation("Codebook");

                    b.Navigation("Preklady");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRoHarmonizovanyKod", b =>
                {
                    b.HasOne("ElectronicMedicalCert.Domain.Entities.PosudekRoZpusobilost", "PosudekRoZpusobilost")
                        .WithMany("HarmonizovaneKody")
                        .HasForeignKey("PosudekRoZpusobilostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosudekRoZpusobilost");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRoHarmonizovanyKodSkupinaRo", b =>
                {
                    b.HasOne("ElectronicMedicalCert.Domain.Entities.PosudekRoHarmonizovanyKod", "PosudekRoHarmonizovanyKod")
                        .WithMany("SkupinaRo")
                        .HasForeignKey("PosudekRoHarmonizovanyKodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosudekRoHarmonizovanyKod");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRoHistorie", b =>
                {
                    b.HasOne("ElectronicMedicalCert.Domain.Entities.PosudekRo", "PosudekRo")
                        .WithMany("Historie")
                        .HasForeignKey("PosudekRoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosudekRo");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRoNarodniKod", b =>
                {
                    b.HasOne("ElectronicMedicalCert.Domain.Entities.PosudekRoZpusobilost", "PosudekRoZpusobilost")
                        .WithMany("NarodniKody")
                        .HasForeignKey("PosudekRoZpusobilostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosudekRoZpusobilost");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRoSkupina", b =>
                {
                    b.HasOne("ElectronicMedicalCert.Domain.Entities.PosudekRoZpusobilost", "PosudekRoZpusobilost")
                        .WithMany("SkupinyRidicskehoOpravneni")
                        .HasForeignKey("PosudekRoZpusobilostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosudekRoZpusobilost");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRoZpusobilost", b =>
                {
                    b.HasOne("ElectronicMedicalCert.Domain.Entities.PosudekRo", "PosudekRo")
                        .WithMany("Zpusobilosti")
                        .HasForeignKey("PosudekRoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosudekRo");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.Codebook", b =>
                {
                    b.Navigation("Polozky");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRo", b =>
                {
                    b.Navigation("Historie");

                    b.Navigation("Zpusobilosti");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRoHarmonizovanyKod", b =>
                {
                    b.Navigation("SkupinaRo");
                });

            modelBuilder.Entity("ElectronicMedicalCert.Domain.Entities.PosudekRoZpusobilost", b =>
                {
                    b.Navigation("HarmonizovaneKody");

                    b.Navigation("NarodniKody");

                    b.Navigation("SkupinyRidicskehoOpravneni");
                });
#pragma warning restore 612, 618
        }
    }
}
